config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get 'charts/drivers_rank'
  
  
  get 'charts/drivers_points'
  get 'charts/wins_pie_chart'
  get 'charts/drivers_rank'
  
  get 'api/drivers'
  get 'api/results'
  get 'api/races'

  get '/about', to: 'static_pages#about'
  get '/home', to: 'static_pages#home' 
  get '/twitterfeed', to: 'tweets#index'
  get '/piecharts', to: 'charts#wins_form'
  get '/columncharts', to: 'charts#column_chart_form'
  get '/linecharts', to: 'charts#line_chart_form'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :races
  resources :results
  resources :drivers

  match '*a', :to => 'error#not_found', via: :get
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/race.rb
class Race < ApplicationRecord
	has_many :results
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  # GET /races
  # GET /races.json
  def index
    @races = Race.all
  end

  # GET /races/1
  # GET /races/1.json
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url, notice: 'Race was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:year, :round, :circuit_id, :name, :date)
    end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= form_with(model: race, local: true) do |form| %>
  <% if race.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
      <% race.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :race_year %>
  </div>

  <div class="field">
    <%= form.label :round %>
    <%= form.number_field :round, id: :race_round %>
  </div>

  <div class="field">
    <%= form.label :circuit_id %>
    <%= form.number_field :circuit_id, id: :race_circuit_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :race_name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :race_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/races/edit.html.erb
<h1>Editing Race</h1>

<%= render 'form', race: @race %>

<%= link_to 'Show', @race %> |
<%= link_to 'Back', races_path %>

app/views/races/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Races</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Round</th>
      <th>Circuit</th>
      <th>Name</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @races.each do |race| %>
      <tr>
        <td><%= race.year %></td>
        <td><%= race.round %></td>
        <td><%= race.circuit_id %></td>
        <td><%= race.name %></td>
        <td><%= race.date %></td>
        <td><%= link_to 'Show', race %></td>
        <td><%= link_to 'Edit', edit_race_path(race) %></td>
        <td><%= link_to 'Destroy', race, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Race', new_race_path %>

app/views/races/new.html.erb
<h1>New Race</h1>

<%= render 'form', race: @race %>

<%= link_to 'Back', races_path %>

app/views/races/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @race.year %>
</p>

<p>
  <strong>Round:</strong>
  <%= @race.round %>
</p>

<p>
  <strong>Circuit:</strong>
  <%= @race.circuit_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @race.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @race.date %>
</p>

<%= link_to 'Edit', edit_race_path(@race) %> |
<%= link_to 'Back', races_path %>