config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get 'charts/drivers_rank'
  
  
  get 'charts/drivers_points'
  get 'charts/wins_pie_chart'
  get 'charts/drivers_rank'
  
  get 'api/drivers'
  get 'api/results'
  get 'api/races'

  get '/about', to: 'static_pages#about'
  get '/home', to: 'static_pages#home' 
  get '/twitterfeed', to: 'tweets#index'
  get '/piecharts', to: 'charts#wins_form'
  get '/columncharts', to: 'charts#column_chart_form'
  get '/linecharts', to: 'charts#line_chart_form'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :races
  resources :results
  resources :drivers

  match '*a', :to => 'error#not_found', via: :get
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/result.rb
class Result < ApplicationRecord
	belongs_to :driver
	belongs_to :race
	
	def self.points_compare
		Result.includes(:race).order('points desc').limit(10).pluck("races.name, points")
	end


	def self.wins_by_year
		Result.includes(:race).group(:position).where('races.year =' + $year).pluck("position, count(position) as points_number")
	end

	def self.column_chart
		Result.includes(:driver).includes(:race).group(:surname).order('sum(points) desc').where('races.year =' + $year_column_chart).pluck("surname, sum(points) as overall_points")
	end

	def self.rank_change
		Result.includes(:race).where('races.year = 2017').pluck("races.name, position")
	end
	
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:race_id, :driver_id, :constructor_id, :grid, :position, :rank)
    end
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_form.html.erb
<%= form_with(model: result, local: true) do |form| %>
  <% if result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :race_id %>
    <%= form.number_field :race_id, id: :result_race_id %>
  </div>

  <div class="field">
    <%= form.label :driver_id %>
    <%= form.number_field :driver_id, id: :result_driver_id %>
  </div>

  <div class="field">
    <%= form.label :constructor_id %>
    <%= form.number_field :constructor_id, id: :result_constructor_id %>
  </div>

  <div class="field">
    <%= form.label :grid %>
    <%= form.number_field :grid, id: :result_grid %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position, id: :result_position %>
  </div>

  <div class="field">
    <%= form.label :rank %>
    <%= form.number_field :rank, id: :result_rank %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Results</h1>

<table>
  <thead>
    <tr>
      <th>Race</th>
      <th>Driver</th>
      <th>Constructor</th>
      <th>Grid</th>
      <th>Position</th>
      <th>Rank</th>
      <th>Points</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.race_id %></td>
        <td><%= result.driver_id %></td>
        <td><%= result.constructor_id %></td>
        <td><%= result.grid %></td>
        <td><%= result.position %></td>
        <td><%= result.rank %></td>
        <td><%= result.points %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Race:</strong>
  <%= @result.race_id %>
</p>

<p>
  <strong>Driver:</strong>
  <%= @result.driver_id %>
</p>

<p>
  <strong>Constructor:</strong>
  <%= @result.constructor_id %>
</p>

<p>
  <strong>Grid:</strong>
  <%= @result.grid %>
</p>

<p>
  <strong>Position:</strong>
  <%= @result.position %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @result.rank %>
</p>

<p>
  <strong>Points:</strong>
  <%= @result.points %>
</p>


<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>