config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get 'charts/drivers_rank'
  
  
  get 'charts/drivers_points'
  get 'charts/wins_pie_chart'
  get 'charts/drivers_rank'
  
  get 'api/drivers'
  get 'api/results'
  get 'api/races'

  get '/about', to: 'static_pages#about'
  get '/home', to: 'static_pages#home' 
  get '/twitterfeed', to: 'tweets#index'
  get '/piecharts', to: 'charts#wins_form'
  get '/columncharts', to: 'charts#column_chart_form'
  get '/linecharts', to: 'charts#line_chart_form'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :races
  resources :results
  resources :drivers

  match '*a', :to => 'error#not_found', via: :get
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/driver.rb
class Driver < ApplicationRecord
	has_many :results
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:forename, :surname, :dob, :nationality)
    end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_with(model: driver, local: true) do |form| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :forename %>
    <%= form.text_field :forename, id: :driver_forename %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname, id: :driver_surname %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.date_select :dob, id: :driver_dob %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality, id: :driver_nationality %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Drivers</h1>

<table>
  <thead>
    <tr>
      <th>Forename</th>
      <th>Surname</th>
      <th>Dob</th>
      <th>Nationality</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.forename %></td>
        <td><%= driver.surname %></td>
        <td><%= driver.dob %></td>
        <td><%= driver.nationality %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<h1>New Driver</h1>

<%= render 'form', driver: @driver %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Forename:</strong>
  <%= @driver.forename %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @driver.surname %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @driver.dob %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @driver.nationality %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>